### ISSUE TITLE
Update description replacing files with file

### ISSUE THREAD

**Issue by mloskot** [Microsoft/cmd-call-graph#1]
The description and the README say:

> A simple tool to generate a call graph for Windows CMD (batch) files. 

IMHO, it should read "for Windows CMD (batch) file."

The "files" suggest one can generate graph for batch scripts `CALL`-ing other batch scripts which, AFAICT, is not the case. Call graph can be generated for single batch file only.

**Comment by mloskot** [comment]
Thanks

**Comment by lupino3** [comment]
Thank you for the feedback! Staying within the boundary of a single file is a design decision, and it was not clear from the text that you suggested to correct.

**Comment by mloskot** [comment]
I see. That's fine. Thank you for the correction.
