### ISSUE TITLE
Execute a full end-to-end test in Travis

### ISSUE THREAD

**Issue by lupino3** [Microsoft/cmd-call-graph#20]
It would be nice to run `dot` on Travis on the output of the tool, to verify that the dot code that it produces is readable by the `dot` tool.

**Comment by GreyCat** [comment]
Given that it's Microsoft project, why not use Azure DevOps for it, actually?

**Comment by lupino3** [comment]
Yeah that's a good point. I'll file an issue for that.

**Comment by lupino3** [comment]
@GreyCat thanks for the suggestion. The migration was pretty easy, and with very little effort I could also add unit tests results reporting and code coverage reporting integrated in the Azure DevOps UI: https://dev.azure.com/cmd-call-graph/cmd-call-graph/_build/results?buildId=8&view=results.

It will also be easy to automate publishing packages to PyPI.
